// <auto-generated />
using Grocery.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Grocery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200414103347_CreateInitialTable")]
    partial class CreateInitialTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Grocery.Models.ProductBrand", b =>
                {
                    b.Property<long>("ProdBrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProdBrandDesc")
                        .HasColumnType("nVarChar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("ProdBrandIndex")
                        .HasColumnType("Int")
                        .HasMaxLength(4);

                    b.Property<string>("ProdBrandName")
                        .IsRequired()
                        .HasColumnType("nVarChar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProdBrandID");

                    b.ToTable("ProductBrand");
                });

            modelBuilder.Entity("Grocery.Models.ProductCategory", b =>
                {
                    b.Property<long>("ProdCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProdCategoryDesc")
                        .HasColumnType("nVarChar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ProdCategoryIndex")
                        .HasColumnType("Int")
                        .HasMaxLength(3);

                    b.Property<string>("ProdCategoryName")
                        .IsRequired()
                        .HasColumnType("nVarChar(30)")
                        .HasMaxLength(30);

                    b.HasKey("ProdCategoryID");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Grocery.Models.UnitsOfMeasurement", b =>
                {
                    b.Property<long>("UOMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UOMDesc")
                        .HasColumnType("nVarChar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("UOMIndex")
                        .HasColumnType("Int")
                        .HasMaxLength(2);

                    b.Property<string>("UOMName")
                        .IsRequired()
                        .HasColumnType("nVarChar(10)")
                        .HasMaxLength(10);

                    b.HasKey("UOMID");

                    b.ToTable("UnitsOfMeasurement");
                });
#pragma warning restore 612, 618
        }
    }
}
